version: "3.9"

services:

  go-app:
    container_name: go-app
    image: go-api-product
    build: .
    ports:
      - "8000:8000"
    depends_on:
    - go_db

  go_db:
    image: postgres:15
    container_name: go_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
